In [1]:
import numpy as np 
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score, ConfusionMatrixDisplay

In [2]:
test_data = pd.read_csv('../Data/data-created/test_data_preprocessed.csv')

In [3]:
X_test = test_data.drop(['loan_status'],axis=1)
y_test = test_data.loan_status

In [4]:
def metrics(matrix):
    TN = matrix[0,0]
    TP = matrix[1,1]
    FP = matrix[0,1]
    FN = matrix[1,0]
    recall = TP/(TP + FN)
    precision = TP/(TP + FP)
    f1_score = 2*recall*precision/(recall+precision)
    return [recall,precision,f1_score]

##### 1) Logistic Regression

In [5]:
with open('../models/logistic_regression.pkl','rb') as f:
    logistic_model = pickle.load(f)

In [6]:
y_pred = logistic_model.predict(X_test)

In [7]:
logistic_confusion = confusion_matrix(y_test, y_pred)

In [8]:
logistic_confusion

array([[4848,  247],
       [ 773,  649]])

##### 2) Gaussian Naive Bayes 

In [9]:
with open('../models/gnb.pkl','rb') as f:
    gnb = pickle.load(f)

In [10]:
y_pred = gnb.predict(X_test)

In [11]:
gnb_confusion = confusion_matrix(y_test,y_pred)

In [12]:
gnb_confusion

array([[4404,  691],
       [ 484,  938]])

##### 3) Random Forrest

In [17]:
with open('../models/random_forrest.pkl','rb') as f:
    random_forrest_model = pickle.load(f)

In [18]:
y_pred = random_forrest_model.predict(X_test)

In [19]:
random_forrest_confusion = confusion_matrix(y_test,y_pred)

In [20]:
random_forrest_confusion

array([[5011,   84],
       [ 551,  871]])

##### 4) XGBoost