In [30]:
import numpy as np 
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score, ConfusionMatrixDisplay

In [31]:
test_data = pd.read_csv('../Data/data-created/test_data_preprocessed.csv')

In [32]:
X_test = test_data.drop(['loan_status'],axis=1)
y_test = test_data.loan_status

In [33]:
def metrics(matrix):
    TN = matrix[0,0]
    TP = matrix[1,1]
    FP = matrix[0,1]
    FN = matrix[1,0]
    recall = TP/(TP + FN)
    precision = TP/(TP + FP)
    f1_score = 2*recall*precision/(recall+precision)
    return [recall,precision,f1_score]

##### 1) Logistic Regression

In [49]:
with open('../models/logistic_regression.pkl','rb') as f:
    logistic_model = pickle.load(f)

In [50]:
y_pred = logistic_model.predict(X_test)

In [51]:
logistic_confusion = confusion_matrix(y_test, y_pred)

In [52]:
logistic_confusion

array([[4848,  247],
       [ 773,  649]])

##### 2) Gaussian Naive Bayes 

In [34]:
with open('../models/gnb.pkl','rb') as f:
    gnb = pickle.load(f)

In [46]:
y_pred = gnb.predict(X_test)

In [47]:
gnb_confusion = confusion_matrix(y_test,y_pred)

In [48]:
gnb_confusion

array([[4404,  691],
       [ 484,  938]])

##### 3) Random Forrest

In [53]:
with open('../models/random_forrest.pkl','rb') as f:
    logistic_model = pickle.load(f)

In [54]:
lolz = logistic_model.predict(X_test)

In [55]:
confusion = confusion_matrix(y_test,lolz)

In [56]:
confusion

array([[5011,   84],
       [ 551,  871]])