In [92]:
import numpy as np 
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score, ConfusionMatrixDisplay

In [93]:
test_data = pd.read_csv('../Data/data-created/test_data_preprocessed.csv')

In [94]:
X_test = test_data.drop(['loan_status'],axis=1)
y_test = test_data.loan_status

In [95]:
def metrics(matrix):
    TN = matrix[0,0]
    TP = matrix[1,1]
    FP = matrix[0,1]
    FN = matrix[1,0]
    recall = TP/(TP + FN)
    precision = TP/(TP + FP)
    f1_score = 2*recall*precision/(recall+precision)
    return [recall,precision,f1_score]

##### 1) Logistic Regression

In [96]:
with open('../models/logistic_regression.pkl','rb') as f:
    logistic_model = pickle.load(f)

In [97]:
y_pred = logistic_model.predict(X_test)

In [98]:
logistic_confusion = confusion_matrix(y_test, y_pred)

In [99]:
logistic_confusion

array([[4848,  247],
       [ 773,  649]])

In [100]:
logistic_metrics = metrics(logistic_confusion)
print(logistic_metrics)

[0.45639943741209565, 0.7243303571428571, 0.5599654874892147]


##### 2) Gaussian Naive Bayes 

In [101]:
with open('../models/gnb.pkl','rb') as f:
    gnb = pickle.load(f)

In [102]:
y_pred = gnb.predict(X_test)

In [103]:
gnb_confusion = confusion_matrix(y_test,y_pred)

In [104]:
gnb_confusion

array([[4404,  691],
       [ 484,  938]])

In [105]:
gnb_metrics = metrics(gnb_confusion)
print(gnb_metrics)

[0.659634317862166, 0.5758133824432167, 0.6148803670927564]


##### 3) Random Forrest

In [106]:
with open('../models/random_forrest.pkl','rb') as f:
    random_forrest_model = pickle.load(f)

In [107]:
y_pred = random_forrest_model.predict(X_test)

In [108]:
random_forrest_confusion = confusion_matrix(y_test,y_pred)

In [109]:
random_forrest_confusion

array([[5011,   84],
       [ 551,  871]])

In [110]:
random_forrest_metrics = metrics(random_forrest_confusion)
print(random_forrest_metrics)

[0.6125175808720112, 0.912041884816754, 0.7328565418594868]


##### 4) XGBoost

In [111]:
with open('../models/xgboost.pkl','rb') as f:
    xgb = pickle.load(f)

In [112]:
y_pred = xgb.predict(X_test)

In [113]:
xgb_confusion = confusion_matrix(y_test,y_pred)

In [114]:
xgb_confusion

array([[4986,  109],
       [ 769,  653]])

In [115]:
xgb_metrics = metrics(xgb_confusion)
print(xgb_metrics)

[0.45921237693389594, 0.8569553805774278, 0.597985347985348]


##### 5) Penalized SVC

In [116]:
with open('../models/penalized-svc.pkl','rb') as f:
    svc = pickle.load(f)

In [117]:
y_pred = svc.predict(X_test)

In [118]:
svc_confusion = confusion_matrix(y_test,y_pred)
svc_confusion

array([[4611,  484],
       [ 386, 1036]])

In [119]:
svc_metrics = metrics(svc_confusion)
print(svc_metrics)

[0.7285513361462729, 0.6815789473684211, 0.7042828008157715]
