In [1]:
import numpy as np 
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score, ConfusionMatrixDisplay

In [2]:
test_data = pd.read_csv('../Data/data-created/test_data_preprocessed.csv')

In [3]:
X_test = test_data.drop(['loan_status'],axis=1)
y_test = test_data.loan_status

In [4]:
def metrics(matrix):
    TN = matrix[0,0]
    TP = matrix[1,1]
    FP = matrix[0,1]
    FN = matrix[1,0]
    recall = TP/(TP + FN)
    precision = TP/(TP + FP)
    f1_score = 2*recall*precision/(recall+precision)
    return [recall,precision,f1_score]

##### 1) Logistic Regression

In [5]:
with open('../models/logistic_regression.pkl','rb') as f:
    logistic_model = pickle.load(f)

In [6]:
y_pred = logistic_model.predict(X_test)

In [7]:
logistic_confusion = confusion_matrix(y_test, y_pred)

In [8]:
logistic_confusion

array([[4848,  247],
       [ 773,  649]])

In [21]:
logistic_metrics = metrics(logistic_confusion)
print(logistic_metrics)

[0.45639943741209565, 0.7243303571428571, 0.5599654874892147]


##### 2) Gaussian Naive Bayes 

In [9]:
with open('../models/gnb.pkl','rb') as f:
    gnb = pickle.load(f)

In [10]:
y_pred = gnb.predict(X_test)

In [11]:
gnb_confusion = confusion_matrix(y_test,y_pred)

In [12]:
gnb_confusion

array([[4404,  691],
       [ 484,  938]])

In [22]:
gnb_metrics = metrics(gnb_confusion)
print(gnb_metrics)

[0.659634317862166, 0.5758133824432167, 0.6148803670927564]


##### 3) Random Forrest

In [13]:
with open('../models/random_forrest.pkl','rb') as f:
    random_forrest_model = pickle.load(f)

In [14]:
y_pred = random_forrest_model.predict(X_test)

In [15]:
random_forrest_confusion = confusion_matrix(y_test,y_pred)

In [16]:
random_forrest_confusion

array([[5011,   84],
       [ 551,  871]])

In [23]:
random_forrest_metrics = metrics(random_forrest_confusion)
print(random_forrest_metrics)

[0.6125175808720112, 0.912041884816754, 0.7328565418594868]


##### 4) XGBoost

In [27]:
with open('../models/xgboost.pkl','rb') as f:
    xgb = pickle.load(f)

In [28]:
y_pred = xgb.predict(X_test)

In [29]:
xgb_confusion = confusion_matrix(y_test,y_pred)

In [30]:
xgb_confusion

array([[4620,  475],
       [ 667,  755]])

In [31]:
xgb_metrics = metrics(xgb_confusion)
print(xgb_metrics)

[0.5309423347398031, 0.6138211382113821, 0.5693815987933636]
